#!/usr/bin/env node
/**
 * Generate `src/assets-gen.ts`: the skill's assets embedded as string constants.
 * The npx package ships real files under `assets/` (primary path); the embedded
 * map is the fallback for single-file bundles (the API-served `sparrow.js` CLI)
 * where no assets directory exists next to the code. Run via the package's
 * `gen-assets` script whenever `assets/` changes; the output is checked in.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const assetsRoot = path.resolve(here, '..', 'assets');
const outFile = path.resolve(here, '..', 'src', 'assets-gen.ts');

/** Collect relative-path → contents for every file under assets/. */
function collect(dir, prefix = '') {
  const out = {};
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if (statSync(full).isDirectory()) Object.assign(out, collect(full, rel));
    else out[rel] = readFileSync(full, 'utf8');
  }
  return out;
}

const assets = collect(assetsRoot);
const body = `/**
 * GENERATED by scripts/gen-assets.mjs — do not edit. Re-run \`pnpm gen-assets\`
 * after changing anything under assets/. Embedded fallback for single-file
 * bundles where the real assets directory does not exist next to the code.
 */
export const EMBEDDED_ASSETS: Record<string, string> = ${JSON.stringify(assets, null, 2)};
`;
writeFileSync(outFile, body);
console.log(`gen-assets: embedded ${Object.keys(assets).length} files → ${outFile}`);
